name: 🚀 Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out this form to help us understand your request.

  - type: checkboxes
    id: checklist
    attributes:
      label: Prerequisites
      description: Please confirm before submitting
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have checked the roadmap and planned features
          required: true
        - label: This is not a bug report (use bug report template instead)
          required: true

  - type: dropdown
    id: package
    attributes:
      label: Which package should this feature be added to?
      description: Select the relevant package
      options:
        - Core Package (craftile/core)
        - Laravel Package (craftile/laravel)
        - New Package
        - Documentation
        - Developer Experience
        - Other
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New functionality
        - Enhancement to existing feature
        - Performance improvement
        - Developer experience improvement
        - Documentation improvement
        - Other
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A clear and concise description of the feature
      placeholder: Provide a brief summary of the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Is your feature request related to a problem? Please describe.
        A clear and concise description of what the problem is.
        Example: I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: |
        A clear and concise description of what you want to happen.
        Include any specific implementation details if you have them.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: |
        A clear and concise description of any alternative solutions
        or features you've considered.

  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: How would this feature be used?
      placeholder: |
        Provide code examples or usage scenarios:

        ```php
        // Example usage
        $example = new Example();
        $result = $example->newFeature();
        ```
      render: markdown

  - type: checkboxes
    id: breaking
    attributes:
      label: Breaking Changes
      description: Would this feature introduce breaking changes?
      options:
        - label: This feature would introduce breaking changes
        - label: This feature is backwards compatible

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the feature request
      placeholder: |
        Any additional information, mockups, links to similar implementations, etc.